numba_is_way_slower:
	python calc_first_observe_numba_is_way_slower.py --n=10 --nobs=10000

continue_after_compiling:
	python calc_continue_call_after_compiling.py --n=10 --nobs=10000

continue_with_cached:
	python calc_with_cache.py --n=100 --nobs=1000